server:
  port: 9042

logging:
  level:
    root: INFO

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  http:
    multipart:
      enabled=false:
  application:
    name: master-server
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/master_dev?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: "000000"

#custom:
#  hadoop:
#    rm:
#      uri: 192.168.1.102:8088
#    nn:
#      uri: 192.168.1.102:50070
#    conf: /home/jixin/imooc_3/naga/naga-server/src/main/resources
#    proxyuser: hadoop
#    hivemetastore: thrift://192.168.1.102:9083
#  task:
#    packageDir: /home/jixin/imoocprojects/naga/packages
#    azkaban:
#      server: http://47.108.140.82:8081
#      user: azkaban
#      password: azkaban
#      execHome: /soft/home/azkaban-exec-server
#    api:
#      server: localhost
#      port: "9042"
#  presto:
#    uri: jdbc:presto://47.108.140.82:9090/hive
#  hive:
#    uri: jdbc:hive2://47.108.140.82:10000/default
#  spark:
#    home: /soft/home/spark-2.4.4-bin-hadoop2.7
#  redis:
#    ip: 127.0.0.1
#    port: 6379
#  ranger:
#    url: http://47.108.140.82:6080
#    user: admin
#    pwd: admin
#    service:
#      hdfs: imooc_hdfs
#      hive: imooc_hive
